# Project information
site_name: System Administration Documentation

# Configuration
theme: material

# Extensions
markdown_extensions:
  - footnotes
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.tasklist:
      custom_checkbox: true

# Table of contents
pages:
  - Home: index.md
  - Initial Server Setup:
    - Checklist: 'initial-server-setup/checklist.md'
    - Initial Firewall Configuration: 'initial-server-setup/firewall.md'
    - Creating Users and Disabling root: 'initial-server-setup/users.md'
    - Webmin: 'initial-server-setup/webmin.md'
    - Intrusion Prevention: 'initial-server-setup/fail2ban.md'
  - Security:
    - Firewall: 'security/firewall.md'
    - Working With SSH Keys: 'security/ssh.md'
    - SSL Encryption: 'security/certbot.md'
  - Monitoring:
    - Introduction to Prometheus: 'monitoring/intro.md'
    - Prometheus: 'monitoring/prometheus.md'
    - Node Exporter: 'monitoring/node.md'
    - PostgreSQL Exporter: 'monitoring/postgres.md'
    - Mysqld Exporter: 'monitoring/mysqld.md'
    - Apache Exporter: 'monitoring/apache.md'
    - Alertmanager: 'monitoring/alertmanager.md'
    - Writing Rules: 'monitoring/rules.md'
  - Databases:
    - MySQL: 'databases/mysql.md'
    - PostgreSQL: 'databases/postgres.md'
  - Automation and Configuration Management:
    - Environment: 'cm/intro.md'
    - Molecule and Docker: 'cm/testing.md'
  - Tips and Tricks:
    - Filesystem and Memory: 'tips-and-tricks/filesystem.md'
    - User Management: 'tips-and-tricks/users.md'
    - Daemons: 'tips-and-tricks/daemons.md'
    - CRON: 'tips-and-tricks/cron.md'
    - Working with git: 'tips-and-tricks/git.md'
    - Docker: 'tips-and-tricks/docker.md'
    - Miscellaneous: 'tips-and-tricks/tips-and-tricks.md'
