# Project information
site_name: System Administration Documentation

# Configuration
theme: material

# Extensions
markdown_extensions:
  - footnotes
  - admonition
  - codehilite
  - toc:
      permalink: true

# Table of content
pages:
  - Home: index.md
  - Initial Server Setup:
    - Checklist: 'initial-server-setup/checklist.md'
    - Initial Firewall Configuration: 'initial-server-setup/firewall.md'
    - Creating Users and Disabling root: 'initial-server-setup/users.md'
  - Monitoring:
    - Why Prometheus: 'monitoring/why-prometheus.md'
